config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: :create
  end
  resources :bookmarks, only: :destroy
  resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  has_many_attached :photos
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { :scope => :list_id, message: 'is already in the list' }
end

app/models/list.rb
class List < ApplicationRecord
  has_many_attached :photos
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, photos: [])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
     @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, photos: [])
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Add a Critic in the bookmark</h1>

      <%= simple_form_for [@list, @bookmark] do |f|%>
      <%= f.association :movie %>
      <%= f.input :comment %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.submit 'submit critic', class:'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
    <h1>Save any kind of movies</h1>
    <h3 class="typed-js"></h3>
  </div>
</div>
<div class="container py-5">
  <div class="d-flex align-items-center justify-content-between mb-3">
    <h3 class="mb-0">My Lists</h3>
    <%= link_to 'Create a movie list', new_list_path, class: 'btn btn-flat' %>
  </div>

  <%#= cl_image_tag("zkooxcciczrny14qaslk",
      width: 150, height: 150,crop: :fit, crop: :thumb, gravity: :face) %>
   <%#= cl_image_tag("un16lyw6kqrzkxeoexft",
       width: 400, height: 300, crop: :fill) %>

  <div class="row">
     <% @lists.each do |list| %>
      <div class="co-12 colsm-6 col-md-4">
        <%= link_to list_path(list), class:'text-decoration-none' do %>
          <div class="card-category" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path('') %>)">
            <%= list.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Add a List</h1>
        <%= simple_form_for(@list) do |f| %>
        <%= f.input :name %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit "Submit comment", class: "btn btn-success" %>
        <% end %>
        <%= link_to 'Back to the Lists', lists_path, class: "btn btn-success" %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <%= link_to 'My lists', lists_path, class: "btn btn-danger" %>

        <h1><%= @list.name %></h1>
        <p><%= link_to '+ Add a new movie in the list', new_list_bookmark_path(@list), class: "btn btn-successs" %></p>

          <h2>Reviews</h2>
            <div class="cards">
              <% @list.bookmarks.each do |bookmark| %>
                <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= @list.photos.each do |photo| %>
                  <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
                    <% end %>
                  <%= bookmark.movie.title %>
                  <%= bookmark.comment %>
                  <%= link_to "",
                        bookmark_path(bookmark),
                        method: :delete,
                        data: { confirm: "Are you sure?" }, class: "far fa-trash-alt"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>